### ISSUE TITLE
Parse error in date.module

### ISSUE THREAD

**Issue by spot-the-cat** [backdrop-contrib/date_basic#1]
<p>After trying to switch to date_basic I get this error: "<em>PHP Parse error:  syntax error, unexpected '[' in date_basic/date.module on line 38</em>".</p>

**Comment by Graham-72** [comment]
Hi @spot-the-cat , I am not seeing that error report myself. What code do you have on that line 38? I have
`
$default_format = str_replace('i', 'i:s', system_date_format_load('short')['pattern']);
`

**Comment by spot-the-cat** [comment]
Hi @Graham-72 -

My humble apologies, I'm an idiot.

I'm running the wrong version of PHP.

Thank you for your time.

Have Fun - Bill
